
# file: ibert_ultrascale_gth_0.xdc
####################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascale_gth_0.xdc
## /___/   / ## \   \  / ##  \___\/\___ ##
##
##
## Generated by Xilinx IBERT 7Series
##**************************************************************************
##
## Icon Constraints
##
#create_clock -name D_CLK -period 3.2 [get_ports gth_sysclkp_i]
#set_clock_groups -group [get_clocks D_CLK -include_generated_clocks] -asynchronous

##gth_refclk lock constraints
##
## set_property PACKAGE_PIN AL12 [get_ports gth_refclk0p_i[0]]
## set_property PACKAGE_PIN AL11 [get_ports gth_refclk0n_i[0]]
## set_property PACKAGE_PIN AK10 [get_ports gth_refclk1p_i[0]]
## set_property PACKAGE_PIN AK9 [get_ports gth_refclk1n_i[0]]
## set_property PACKAGE_PIN AG12 [get_ports gth_refclk0p_i[1]]
## set_property PACKAGE_PIN AG11 [get_ports gth_refclk0n_i[1]]
## set_property PACKAGE_PIN AF10 [get_ports gth_refclk1p_i[1]]
## set_property PACKAGE_PIN AF9 [get_ports gth_refclk1n_i[1]]
## set_property PACKAGE_PIN AA12 [get_ports gth_refclk0p_i[2]]
## set_property PACKAGE_PIN AA11 [get_ports gth_refclk0n_i[2]]
## set_property PACKAGE_PIN Y10 [get_ports gth_refclk1p_i[2]]
## set_property PACKAGE_PIN Y9 [get_ports gth_refclk1n_i[2]]
## set_property PACKAGE_PIN R12 [get_ports gth_refclk0p_i[3]]
## set_property PACKAGE_PIN R11 [get_ports gth_refclk0n_i[3]]
## set_property PACKAGE_PIN P10 [get_ports gth_refclk1p_i[3]]
## set_property PACKAGE_PIN P9 [get_ports gth_refclk1n_i[3]]
##
## Refclk constraints
##
create_clock -period 3.200 -name gth_refclk0_2 [get_ports p_clk0_chan0]
create_clock -period 3.200 -name gth_refclk1_2 [get_ports p_clk1_chan0]
set_clock_groups -asynchronous -group [get_clocks gth_refclk0_2 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gth_refclk1_2 -include_generated_clocks]
create_clock -period 3.200 -name gth_refclk0_5 [get_ports p_clk0_chan1]
create_clock -period 3.200 -name gth_refclk1_5 [get_ports p_clk1_chan1]
set_clock_groups -asynchronous -group [get_clocks gth_refclk0_5 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gth_refclk1_5 -include_generated_clocks]
create_clock -period 3.200 -name gth_refclk0_8 [get_ports p_clk0_chan2]
create_clock -period 3.200 -name gth_refclk1_8 [get_ports p_clk1_chan2]
set_clock_groups -asynchronous -group [get_clocks gth_refclk0_8 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gth_refclk1_8 -include_generated_clocks]
##
## System clock pin locs and timing constraints
##
#set_property PACKAGE_PIN M32 [get_ports gth_sysclkp_i]
#set_property IOSTANDARD LVDS [get_ports gth_sysclkp_i]


