
# file: ibert_ultrascale_gty_0.xdc
####################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascale_gty_0.xdc
## /___/   / ## \   \  / ##  \___\/\___ ##
##
##
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
## Icon Constraints
##
#create_clock -name D_CLK -period 5.0 [get_ports gty_sysclkp_i]
#set_clock_groups -group [get_clocks D_CLK -include_generated_clocks] -asynchronous

##
##gtrefclk lock constraints
##
## set_property PACKAGE_PIN AD32 [get_ports gty_refclk0p_i[0]]
## set_property PACKAGE_PIN AD33 [get_ports gty_refclk0n_i[0]]
## set_property PACKAGE_PIN AC30 [get_ports gty_refclk1p_i[0]]
## set_property PACKAGE_PIN AC31 [get_ports gty_refclk1n_i[0]]
## set_property PACKAGE_PIN V32 [get_ports gty_refclk0p_i[1]]
## set_property PACKAGE_PIN V33 [get_ports gty_refclk0n_i[1]]
## set_property PACKAGE_PIN U30 [get_ports gty_refclk1p_i[1]]
## set_property PACKAGE_PIN U31 [get_ports gty_refclk1n_i[1]]
## set_property PACKAGE_PIN P32 [get_ports gty_refclk0p_i[2]]
## set_property PACKAGE_PIN P33 [get_ports gty_refclk0n_i[2]]
## set_property PACKAGE_PIN N30 [get_ports gty_refclk1p_i[2]]
## set_property PACKAGE_PIN N31 [get_ports gty_refclk1n_i[2]]
## set_property PACKAGE_PIN M32 [get_ports gty_refclk0p_i[3]]
## set_property PACKAGE_PIN M33 [get_ports gty_refclk0n_i[3]]
## set_property PACKAGE_PIN L30 [get_ports gty_refclk1p_i[3]]
## set_property PACKAGE_PIN L31 [get_ports gty_refclk1n_i[3]]
##
## Refclk constraints
##
create_clock -period 3.200 -name gtrefclk0_1 [get_ports p_clk0_chan4]
create_clock -period 3.200 -name gtrefclk1_1 [get_ports p_clk1_chan4]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_1 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_1 -include_generated_clocks]
create_clock -period 3.200 -name gtrefclk0_4 [get_ports p_clk0_chan5]
create_clock -period 3.200 -name gtrefclk1_4 [get_ports p_clk1_chan5]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_4 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_4 -include_generated_clocks]
create_clock -period 3.200 -name gtrefclk0_6 [get_ports p_clk0_chan6]
create_clock -period 3.200 -name gtrefclk1_6 [get_ports p_clk1_chan6]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_6 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_6 -include_generated_clocks]
create_clock -period 5.000 -name gtrefclk0_7 [get_ports p_util_clk_chan1]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_7 -include_generated_clocks]
##
## System clock pin locs and timing constraints
##
#set_property PACKAGE_PIN M32 [get_ports gty_sysclkp_i]
#set_property IOSTANDARD LVDS [get_ports gty_sysclkp_i]

