
# file: ibert_ultrascale_gty_0.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascale_gty_0.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
## Icon Constraints
##
create_clock -name D_CLK -period 5.0 [get_ports p_clk_200a]
set_clock_groups -group [get_clocks D_CLK -include_generated_clocks] -asynchronous

set_property C_CLK_INPUT_FREQ_HZ 200000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clk]

##
##gtrefclk lock constraints
##
# set_property PACKAGE_PIN R36 [get_ports gty_refclk0p_i[0]] */
# set_property PACKAGE_PIN R37 [get_ports gty_refclk0n_i[0]] */
# set_property PACKAGE_PIN N36 [get_ports gty_refclk1p_i[0]] */
# set_property PACKAGE_PIN N37 [get_ports gty_refclk1n_i[0]] */
# set_property PACKAGE_PIN H11 [get_ports gty_refclk0p_i[1]] */
# set_property PACKAGE_PIN H10 [get_ports gty_refclk0n_i[1]] */
# set_property PACKAGE_PIN F11 [get_ports gty_refclk1p_i[1]] */
# set_property PACKAGE_PIN F10 [get_ports gty_refclk1n_i[1]] */
##
## Refclk constraints
##
create_clock -name gtrefclk0_8 -period 3.2 [get_ports p_clk0_chan7]
create_clock -name gtrefclk1_8 -period 3.2 [get_ports p_clk1_chan7]
set_clock_groups -group [get_clocks gtrefclk0_8 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_8 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_18 -period 3.2 [get_ports p_clk0_chan3]
create_clock -name gtrefclk1_18 -period 3.2 [get_ports p_clk1_chan3]
set_clock_groups -group [get_clocks gtrefclk0_18 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_18 -include_generated_clocks] -asynchronous
##
## System clock pin locs and timing constraints
##
# set_property PACKAGE_PIN BA35 [get_ports gty_sysclkp_i] */
# set_property IOSTANDARD LVDS [get_ports gty_sysclkp_i] */
